version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: nhatrinh269
      MYSQL_DATABASE: hive
      MYSQL_USER: nhatrinh269
      MYSQL_PASSWORD: nhatrinh269
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  hadoop-base:
    build:
      context: ./hadoop-base
    image: hadoop-base

  namenode:
    build:
      context: ./namenode
    image: hadoop-base
    container_name: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - namenode:/hadoop/dfs/name
    depends_on:
      - hadoop-base

  datanode:
    build:
      context: ./datanode
    image: hadoop-base
    container_name: datanode
    ports:
      - "9864:9864"
    volumes:
      - datanode:/hadoop/dfs/data
    depends_on:
      - namenode

  resourcemanager:
    build:
      context: ./resourcemanager
    image: hadoop-base
    container_name: resourcemanager
    ports:
      - "8088:8088"
    depends_on:
      - namenode

  nodemanager:
    build:
      context: ./nodemanager
    image: hadoop-base
    container_name: nodemanager
    ports:
      - "8042:8042"
    depends_on:
      - resourcemanager

  hbase:
    build:
      context: ./hbase
    image: hadoop-base
    container_name: hbase
    ports:
      - "16010:16010"
      - "9090:9090"
    volumes:
      - hbase-data:/opt/hbase/data
    environment:
      - CLUSTER_NAME=test
    depends_on:
      - namenode

  hive:
    build:
      context: ./hive
    image: hadoop-base
    container_name: hive
    ports:
      - "10000:10000"
    volumes:
      - hive-data:/opt/hive/data
    environment:
      - CLUSTER_NAME=test
    depends_on:
      - namenode
      - mysql

  jupyter_notebook:
    build: ./jupyter_notebook
    container_name: jupyter_notebook
    volumes:
      - work:/home/jovyan/work
    ports:
      - 8888:8888
    environment:
      - CLUSTER_NAME=test
    depends_on:
      - namenode
    command: "start-notebook.sh --NotebookApp.token="

volumes:
  mysql-data:
  namenode:
  datanode:
  hbase-data:
  hive-data:
  work:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/nhatrinh/docker/hadoop_system/work"

